CREATE DATABASE FinancialAssistant_cdb
USER SYS IDENTIFIED BY 123098
USER SYSTEM IDENTIFIED BY 098123
EXTENT MANAGEMENT LOCAL
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
DATAFILE 'FinancialAssistant.dbf' SIZE 100M
AUTOEXTEND ON
NEXT 5M MAXSIZE UNLIMITED
DEFAULT COLLATION "USING_NLS_COMP";