DROP INDEX DATE_INDEX;
ALTER USER ADMIN QUOTA UNLIMITED ON SYSTEM;

CREATE INDEX DATE_INDEX ON ADMIN.Saves (SaveDate) TABLESPACE FA_TS;
COMMIT;

SELECT INDEX_NAME, TABLE_NAME, TABLESPACE_NAME
FROM USER_INDEXES
WHERE TABLE_NAME = 'SAVES' AND INDEX_NAME = 'DATE_INDEX';

SELECT * FROM USER_INDEXES  WHERE TABLE_NAME = 'Saves';